openbook-dex/openbook-v2

programs/openbook-v2/src/logs.rs, programs/openbook-v2/src/state/market.rs
Gentlefolks, it is with utmost respect and regard that I present to thee an analysis of the present state of `MarketIndex` - verily, a `u16`. This allows for a respectable number of markets - 65,536 to be exact. 
However, at the Market's girth of 2744 bytes, someone can create a `Market` for the petite price of 0.01998912 SOL. Thusly, a malevolent griefer could use up every index for 1310 SOL, or ~$28k at the current market price of $21.31. This would prevent users from creating new markets.
However, a thought occurs to me - a change in MarketIndex to a u32 would markedly elevate this cost to $1.8B. Alternatively, we could consider a shift to a u64, which would result in a staggering cost of $7e18.
=> fix: increase `MarketIndex` from `u16` -> `u32`

programs/openbook-v2/src/instructions/consume_events.rs, programs/openbook-v2/src/instructions/place_order.rs, programs/openbook-v2/src/instructions/place_take_order.rs, programs/openbook-v2/src/state/open_orders_account.rs, programs/openbook-v2/src/state/orderbook/book.rs, programs/openbook-v2/tests/cases/mod.rs, programs/openbook-v2/tests/cases/test.rs, programs/openbook-v2/tests/cases/test_fees.rs, programs/openbook-v2/tests/cases/test_oracle_peg.rs, programs/openbook-v2/tests/cases/test_order_types.rs, programs/openbook-v2/tests/cases/test_place_order_remaining.rs, programs/openbook-v2/tests/cases/test_self_trade.rs, programs/openbook-v2/tests/cases/test_take_order.rs, programs/openbook-v2/tests/program_test/client.rs
In this way, no event is emitted to the event_queue and therefore the system is crankless as long as the maker is known when placing the order.
=> Process event on place order if remaining acc matches

programs/openbook-v2/src/accounts_ix/create_market.rs, programs/openbook-v2/src/instructions/create_market.rs, programs/openbook-v2/src/lib.rs, programs/openbook-v2/tests/program_test/client.rs
fuzzing the input arguments require that the types implements `Arbitrary`, which `pubkey` doesn't.
Move the market admin accs to the accounts context to be able to derive arbitrary trait
=> create market pass admin as accounts

programs/openbook-v2/src/state/open_orders_account.rs, programs/openbook-v2/src/state/orderbook/book.rs, programs/openbook-v2/src/state/orderbook/queue.rs
so that the value is preserved in case the maker, after a partial fill, cancels his orders
=> store peg_limit in the fillevent

programs/openbook-v2/src/logs.rs, programs/openbook-v2/src/state/open_orders_account.rs
This PR adds an OpenOrdersPositionLog to the openbook program. It's analagous to the OpenOrdersBalanceLog in Openbook V1 (which was very useful for tracking user balances over time)
https://github.com/openbook-dex/program/blob/c85e56deeaead43abbc33b7301058838b9c5136d/dex/src/state.rs#L1369
=> add OpenOrdersPositionLog

Anchor.toml
I'm working on something that CPIs into openbook, and I forgot that the repo uses non-anchor tests so Anchor.toml isn't used the same way, so I pulled in the wrong program ID. This updates it so that someone else wouldn't make the same mistake.
=> Fix program ID in Anchor.toml

ts/client/src/client.ts
I'm currently working on an `openbook_twap` program that sits on top of `openbook_v2` and, for specific markets, feeds prices into a TWAP aggregator. These changes made the TS client more convenient to work with, and I think would be generally beneficial. They include:
- return the market's pubkey from `createMarket`, so that you can use the market in future instructions
- allow the client to pass the market Keypair, so that I can first generate a keypair, then generate a PDA that will be the Market's `open_orders_authority`, then create the market
=> Modify the ts client to allow for an `openbook_twap` program

ts/client/src/client.ts
Caveat emptor, this is a non-backwards-compatible change. But I think it makes the interface a little simpler, since you don't have to dig up the OpenBook program ID.
Alternatively, we could put `programId` after `opts`, if we think that there's a higher probability of someone changing the `opts` than the `programId`
=> Add a default `programId` to ts client

ts/client/src/client.ts, ts/client/src/utils/rpc.ts
I use a Solana testing framework called
[bankrun](https://github.com/kevinheavey/solana-bankrun/tree/main). This patch makes the SDK compatible with bankrun.
=> Make SDK compatible with bankrun

ts/client/src/client.ts
This way allows owners other than the payer and also allows you to just generate instructions, which is useful if you don't have a `Keypair` (as is the case in a UI).
=> Refactor ts open orders creation

package.json
My webapp doesn't work with the fs dependency (no file system in web browser), and I figured eslint-config-prettier was also meant as a dev dep.
=> Remove `fs` and `eslist-config-prettier` from cli deps

.github/workflows/ci-code-review-rust.yml, Cargo.lock, SECURITY.md, lib/client/Cargo.toml, programs/openbook-v2/Cargo.toml, programs/openbook-v2/src/lib.rs
Hey team
This PR adds a couple of security reserch related features.
1. A relatively generic git security readme asking for responsible disclosure. Will leave it up to you how you want to word the potential bounty aspect. I've left it open to interpretation
2. On chain security text in case researchers discover onchain security issues and are not familiar with git/contact directions. This leads them to where you want them to engage. I.e. this section.:
3. Bumps a number of dep versions 
The PR also fixes a build issue that I introduced from applying `clippy` recommendations. This part has been re-added in`Cargo.toml` files: `cargo-features = ["workspace-inheritance"]`
To that effect, I also included a build test step in the CI workflow.
=> feat: on chain security info

lib/client/src/client.rs
fixes an issue where the PDA seeds in the client function `OpenBookClient::create_open_orders_account` do not match the smart contract seeds
=> client: fix pda seeds in create_open_orders_account

programs/openbook-v2/src/accounts_ix/settle_funds.rs, programs/openbook-v2/src/accounts_ix/settle_funds_expired.rs, programs/openbook-v2/src/state/open_orders_account.rs
allows the delegate to settle funds only to the oo owner accounts
=> allows the delegate to settle funds

programs/openbook-v2/fuzz/Cargo.lock, programs/openbook-v2/fuzz/fuzz_targets/multiple_orders.rs, programs/openbook-v2/src/instructions/close_open_orders_account.rs, programs/openbook-v2/src/instructions/create_open_orders_account.rs, programs/openbook-v2/src/logs.rs, programs/openbook-v2/src/state/open_orders_account.rs, programs/openbook-v2/src/state/orderbook/mod.rs, programs/openbook-v2/tests/cases/test_oracle_peg.rs
In order to simplify accounting for MM, they should know the quote amount present on the book by querying only the ooa
=> Add bids_quote_lots to ooa

.github/workflows/ci-verified-build.yml, .github/workflows/release-verifiable-build.yml, programs/openbook-v2/Cargo.toml, programs/openbook-v2/src/lib.rs
PR contains two changes:
1. Adds source release version and source revision metadata to the onchain security page on https://explorer.solana.com
2. Introduces a workflow that is triggered when publishing a new release. This workflow creates a verifiable build and a software bill of materials artifact, and attaches them to the release. Increases integrity and transparency of releases
=> feat: security txt and build integrity

ts/client/src/market.ts
quoteLotsToUiConverter taking a constant QUOTE_DECIMALS which assumed quote token decimals were 6, instead of fetching actual quoteDecimals from MarketAccount.
=> quoteLotsToUiConverter pass correct quote decimals

ts/client/src/client.ts
The program requires it as a signer.
https://github.com/openbook-dex/openbook-v2/blob/master/programs/openbook-v2/src/accounts_ix/settle_funds.rs#L11
The default key that the client otherwise uses does not work because the web3.js client fails signature validation in preflight.
=> Do not allow penalty payer to be null in settle funds in ts client

idl/openbook_v2.json, programs/openbook-v2/src/instructions/cancel_all_and_place_orders.rs, programs/openbook-v2/src/instructions/cancel_all_orders.rs, programs/openbook-v2/src/instructions/cancel_order_by_client_order_id.rs, programs/openbook-v2/src/instructions/prune_orders.rs, programs/openbook-v2/src/lib.rs, programs/openbook-v2/src/state/orderbook/book.rs, programs/openbook-v2/tests/cases/test_edit_order.rs, programs/openbook-v2/tests/cases/test_oracle_peg.rs, programs/openbook-v2/tests/program_test/client.rs, ts/client/src/client.ts, ts/client/src/openbook_v2.ts, ts/client/src/test/market.ts
cancel by client id previously would fail the transaction making it very difficult to implement cancelling a subset of orders (e.g. assigned to an individual trading engine inside a multi strategy fund). if an order is filled while the users transaction is inflight, a direct cancel with a client id can fail if there is no such order.
in my opinion this version is better, it is easier to use
also removed the limit on prune orders, as the OO account is anyways limited to 24 orders, there's not a lot of value in an explicit limit argument.
=> cancel by client_id iterates and fails silently

programs/openbook-v2/src/instructions/cancel_all_and_place_orders.rs, programs/openbook-v2/src/instructions/place_order.rs, programs/openbook-v2/src/instructions/place_take_order.rs, programs/openbook-v2/src/state/market.rs, programs/openbook-v2/src/state/orderbook/book.rs, programs/openbook-v2/src/state/orderbook/mod.rs
currently `oracle_price` is converted to `oracle_price_lots` inside book’s new_order
https://github.com/openbook-dex/openbook-v2/blob/706186b299e8a59c639e583f87dbc4e09d996d20/programs/openbook-v2/src/state/orderbook/book.rs#L82
hence, when placing multiple orders, the same (possible costly -i80f48 math-) operation will be repeated several times. This PR makes the calculation before the new_order loop so it's only computed once per ix with the intention of saving some CUs
=> add oracle_price_lots fn

programs/openbook-v2/src/accounts_ix/settle_funds.rs
The owner has to sign, but its data is not even read.
=> settle ix: don't require a mut owner

programs/openbook-v2/src/state/orderbook/heap.rs, programs/openbook-v2/src/state/orderbook/nodes.rs, programs/openbook-v2/src/state/orderbook/ordertree.rs
They were causing errors with some rust versions.
=> Remove redundant Pod and Zeroable derives for zero_copy structs

programs/openbook-v2/src/state/orderbook/nodes.rs, programs/openbook-v2/src/state/orderbook/ordertree.rs
Otherwise casting local variables of type AnyNode can fail (because the target type's alignment may be larger than AnyNode's)
=> Ensure all ordertree nodes share an alignment

ts/client/src/client.ts
This fixes an error when decoding a v2 market account due to a mismatch between the struct name defined in the idl and the provided value
=> update market account struct name to match idl value

lib/client/src/client.rs
The Ting wasn't exposed in the client, although our holy [`openbook`](https://github.com/GigaDAO/openbook) client will expose 'em all in a nice 'n clean way,  so I decided to implement it, Cheers!
=> feat: implement `cancel_all_and_place_orders` client func
